### PR TITLE
Functionality to add additional resources in the app bundle

### PR DESCRIPTION
**Pull request by waqqasjabbar**
One can copy additional resources in the DMG but I wanted to add additional resources within the app bundle itself. I added a generic way to add any file or directory to any location within the bundle.

### CODE REVIEW

**Review by perdian — APPROVED** [review]
I really like that addition! 👍

@waqqasjabbar I'm really curious about the actual use case: What are the circumstances where you want (or better: need) to add additional resources directly to the app bundle?

**Comment by perdian** [comment]
Will release this as `1.11.0` as soon as I can reach Maven Central (`oss.sonatype.org` seems to be down at the moment).

**Comment by waqqasjabbar** [comment]
I wanted to make an network extension part of the app. It needs to be
placed in Content/PlugIns directory.

Thanks for approving the PR

**Comment by perdian** [comment]
Released to Maven Central as [`1.11.0`](https://search.maven.org/artifact/de.perdian.maven.plugins/macosappbundler-maven-plugin/1.11.0/maven-plugin)

**Pull request merged**
