### PR TITLE
add support for showing splash screen

### PR DESCRIPTION
**Pull request by nybbs2003**

### CODE REVIEW

**Comment by perdian** [comment]
I don't see how the splash file is actually **used** later on. The PR added the `JVMSplashFile` property into the `Info.plist` file but from what I can see that information isn't used by the launcher (or any other component) when the application is launched. 

Am I missing something?

**Comment by nybbs2003** [comment]
The splash file is used as an image shown in the middle of the screen from the moment when launcher is started to everything is loaded and the `main` mathod is called.

You can see an example [here](https://github.com/eth3-peth/pearletj/releases/tag/v0.1.5-snapshot)

**Comment by perdian** [comment]
I still do not see how the `JVMSplashFile` is actually used. Yes, it's being added into the `Info.plist` file but that's it.

The launcher doesn't use the value in any way so the Java application itself is completely unaware that a splash file has been defined (and thus cannot use it).

**Comment by perdian** [comment]
Closing this PR as it doesn't add any value to the existing project.

Please provide a [minimal reproducible example](https://minimum-reproduction.wtf/) if you want to re-introduce the feature request.

**Pull request closed without merging**
