### PR TITLE
name for jre folder (its not a jdk)

### PR DESCRIPTION
**Pull request by ChristopherBruno78**
PR proposes to rename the folder the private JRE is placed. Currently its called jdk. Usually only JRE will be distributed. This PR renames the folder to Runtime.jre

### CODE REVIEW

**Comment by perdian** [comment]
I like the general idea but (and I know we're starting to split hairs here) but the included runtime **can** be a **jdk** and not "only" a **jre** so the name might be misleading.

What do you think about renaming this to a neutral `runtime` folder with the `Java` directory?

This way **all** the Java specific resource would be located within the `Java` directory, something like:

```
$ tree Example.app

Exmple.app
- Contents
  - Java
    - classpath
    - runtime
  - MacOS
  - Resources
```

**Comment by ChristopherBruno78** [comment]
That would be good by me!

**Comment by ChristopherBruno78** [comment]
The reason for the .jre is this extension is typical for jres downloaded for MacOS...for example zulu-17.jre etc.

**Comment by perdian** [comment]
Released to Maven Central as `1.17.1`

**Pull request merged**
